version: '3.8'
services:
  server:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass 63nTa6UlGeRipER5HIlInTH5hoS3ckL4
    volumes: 
      - server:/data
volumes:
  server:
    driver: local
